version: "3"

services:

  nitter:
    image: ghcr.io/privacydevel/nitter:master
    container_name: nitter
    ports:
      - "127.0.0.1:8083:8080" # Replace with "8080:8080" if you don't use a reverse proxy
    volumes:
      - ./nitter.conf:/src/nitter.conf:Z,ro
      - ./sessions.jsonl:/src/sessions.jsonl:Z,ro # Run get_sessions.py to get the credentials
    restart: unless-stopped
    depends_on:
      - nitter-redis
    # healthcheck:
    #   test: wget -nv --tries=1 --spider http://127.0.0.1:8080/Jack/status/20 || exit 1
    #   interval: 30s
    #   timeout: 5s
    #   retries: 2
    user: "998:998"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks: [nitter_network]

  nitter-redis:
    image: valkey/valkey:7.2.5-alpine
    container_name: nitter-redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - nitter-redis:/data:rw
    restart: unless-stopped
    # healthcheck:
    #   test: redis-cli ping
    #   interval: 30s
    #   timeout: 5s
    #   retries: 2
    user: "999:1000"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    networks: [nitter_network]

volumes:
  nitter-redis:

networks:
  nitter_network:
    enable_ipv6: true
